### PR TITLE
Add Podfile to each app so they can use CocoaPods to retrieve Here SD…

### PR DESCRIPTION
**Pull request by JohnLXiang**
…K directly.Update README file to reflect this change.

### CODE REVIEW

**Comment by sschuberth** [comment]
Please re-format the commit message of 4cfab539e227753750663d54fe10300fd7dbe737 so that the title is only about 75 chars in length, then have a blank line, followed by the commit message body with the rest of the text.

**Comment by sschuberth** [comment]
BTW, does this change mean we're hosting the HERE SDK for iOS on CocoaPods now already?

**Comment by JohnLXiang** [comment]
Not yet, our plan is to merge this branch to master after 3.4 is released.

**Comment by JohnLXiang** [comment]
I'm closing this pull request and delete the branch for time being, will re-push it after 3.4 is on.

**Pull request closed without merging**
